### ISSUE TITLE
[Cassandra]  Not all configurations exposed at package options level

### ISSUE THREAD

**Issue by fksimon** [mesosphere/dcos-commons#1046]
Created a ticket, but also sharing here.   This was against the old framework but still seems to apply, the properties below are available for configuration but not exposed at the package options level.

https://jira.mesosphere.com/browse/DCOS_CASSANDRA-42

dcos package install --options myoptions.json cassandra
I receive the error below
Unexpected properties: ['endpoint_snitch', 'gc_warn_threshold_in_ms', 'key_cache_size_in_mb',
'memtable_cleanup_threshold', 'memtable_flush_writers', 'permissions_validity_in_ms',
'phi_convict_threshold', 'roles_update_interval_in_ms', 'roles_validity_in_ms']
myoptions file is
{{{ "service": { "name": "cassandra-c1", "data_center": "Cassandra", "principal": "cassandra_principal", "cpus": 0.1, "mem": 512, "heap": 256 }, "nodes": { "cpus": 2.0, "mem": 4096, "disk": 10240, "disk_type": "ROOT", "heap": { "size": 1024, "new": 100 }, "count": 1, "seeds": 1 }, "cassandra": { "authenticator": "PasswordAuthenticator", "authorizer": "CassandraAuthorizer", "concurrent_reads": 96, "concurrent_writes": 128, "compaction_throughput_mb_per_sec": 128, "endpoint_snitch": "GossipingPropertyFileSnitch", "gc_warn_threshold_in_ms": 500, "key_cache_size_in_mb": 256, "memtable_allocation_type": "heap_buffers", "memtable_cleanup_threshold": 0.6, "memtable_flush_writers": 8, "num_tokens": 64, "permissions_validity_in_ms": 60000, "phi_convict_threshold": 12, "roles_validity_in_ms": 60000, "roles_update_interval_in_ms": 5000 } }}}
It appears in issue #283 they were added to the application configuration. I also see them in the schedule.yml as environment replacements.
It appears they were never added to the universe config file so are being rejected at that point when used in the options file. They do not appear when you run
dcos package install cassandra --config
Environment was DCOS 1.8.7 and 1.9-rc3.
dcos package describe cassandra
{
"description": "Apache Cassandra running on DC/OS",
"framework": true,
"maintainer": "support@mesosphere.io",
"minDcosReleaseVersion": "1.7",
"name": "cassandra",
"packagingVersion": "3.0",
"postInstallNotes": "DC/OS Apache Cassandra has been successfully installed!\n\n\tDocumentation: https://docs.mesosphere.com/current/usage/service-guides/cassandra/\n\tIssues: https://dcosjira.atlassian.net/projects/CASSANDRA/issues",
"postUninstallNotes": "DC/OS Apache Cassandra service has been uninstalled.\nPlease follow the instructions at https://docs.mesosphere.com/current/usage/service-guides/cassandra/uninstall to remove any persistent state if required.",
"preInstallNotes": "DC/OS Cassandra Service default configuration requires 3 nodes each with 1.5 CPU shares, 5376MB of memory and 11264MB of disk for running Cassandra Nodes. And, 1 node with 0.5 CPU shares, 2048MB of memory for running the service scheduler.",
"selected": true,
"tags": [
"data",
"database",
"nosql"
],
"version": "1.0.25-3.0.10"

**Comment by keithchambers** [comment]
Hi Fran, thanks you for pointing this out.

This is a valid issue we plan to address.

At the moment our Engineering team is focused on delivering some important new features, but we are happy to accept a high quality PR.

**Comment by fksimon** [comment]
I have already verified I can pass them in the JSON directly and they properly configure Cassandra, this is just for the universe package. I suspect it is substantially easier for you, but I can look into.  I'll see what I can do about a PR. 

Cassandra tuning and being able to set those properties is very important to anyone using this framework for large write quantities.   We have seen substantial performance gains manipulating them.  Adding new features without fixing current problems really shouldn't be top priority.  I could see if this was a major code change, but its just packaging mistake.

Properties not in package options:
'endpoint_snitch', 
'gc_warn_threshold_in_ms', 
'key_cache_size_in_mb',
'memtable_cleanup_threshold', 
'memtable_flush_writers', 
'permissions_validity_in_ms',
'phi_convict_threshold', 
'roles_update_interval_in_ms', 
'roles_validity_in_ms'

**Comment by fksimon** [comment]
This appears to be fixed in the latest version, I was able to pass in via options file.
