### ISSUE TITLE
pre-download all the files when packaging  elastic in universe

### ISSUE THREAD

**Issue by scweang** [mesosphere/dcos-commons#1205]
can elastic pre-download all the files when packaging in universe instead of downloading from the remote when installing it?

I've got into a trouble that when installing elastic, it will download a lot of files from remote such as `https://downloads.mesosphere.com/java/jre-8u112-linux-x64-jce-unlimited.tar.gz`. 

I have an unstable network and the downloading may be very slow. What's more frustrating is that mesos will kill the job after 10 minitues and restart it for new downloading... Everytime I see this 77MB file completed 60MB or more I just feel very complex...

As for quick recovery, I think it's also reasonable for packaging it in previously process so that it takes less time for reinstallation.

**Comment by triclambert** [comment]
There's no support for this at the moment.  However, perhaps the mesos-fetcher [cache](http://mesos.apache.org/documentation/latest/fetcher-cache-internals/) could help.
