### ISSUE TITLE
Upload library to Maven Central Repository

### ISSUE THREAD

**Issue by activatedgeek** [mesosphere/dcos-commons#134]
I need to build upon this library but it looks like it is not available on the Maven Central Repository. I think it would be great to have this library released as a versioned JAR artifact rather than cloning and building manually.

**Comment by nickbp** [comment]
We've been uploading artifacts to a maven repository at `downloads.mesosphere.com`. You should be able to configure your project to use that, with something like these examples (gradle configs):
- [dcos-cassandra-service](https://github.com/mesosphere/dcos-cassandra-service/blob/master/build.gradle#L41)
- [dcos-kafka-service](https://github.com/mesosphere/dcos-kafka-service/blob/master/build.gradle#L52)

**Comment by activatedgeek** [comment]
Oh perfect. Sorry about the confusion. I think it is worth mentioning in the README. :) Thanks!
