### ISSUE TITLE
Add common endpoint implementations for config/state storage

### ISSUE THREAD

**Issue by nickbp** [mesosphere/dcos-commons#14]
Similar to the /plan endpoint, we should have commonly defined read-only endpoint(s) for viewing framework configuration and state. This will make it straightforward to have common tooling for accessing this data.

For example, Kafka currently exposes endpoints for listing all available configurations and viewing the id/contents of the active configuration. Something like these could be ported into commons.

**Comment by keithchambers** [comment]
This is a great idea!

**Comment by nickbp** [comment]
Done:
https://github.com/mesosphere/dcos-commons/tree/master/src/main/java/org/apache/mesos/config/api https://github.com/mesosphere/dcos-commons/tree/master/src/main/java/org/apache/mesos/state/api
