### ISSUE TITLE
Bad Request when trying to get authentication token

### ISSUE THREAD

**Issue by enlinxu** [mesosphere/dcos-commons#142]
I am following https://docs.mesosphere.com/1.8/administration/id-and-access-mgt/iam-api/ to get a token for http endpoint access.
So I am posting to http://{DCOS_HOST_NAME}/acs/api/v1/auth/login with the following payload:
{
  "uid": "{MY_DCOS_USERNAME}",
  "password": "{PW}"
}

But I am getting:
{
  "title": "Bad Request",
  "description": "JWT parsing failed"
}

Any help is highly appreciated

**Comment by gabrielhartmann** [comment]
@enlinxu:  Apologies for the late reply.  This repository is an SDK for writing services on DC/OS.  It does not address directly logging into a DC/OS cluster.  This issue is better suited to being addressed by the [Open DC/OS community here](https://dcos.io/community/).
