### ISSUE TITLE
Mount Volumes using TaskSpecification

### ISSUE THREAD

**Issue by gabrielhartmann** [mesosphere/dcos-commons#147]
Internal JIRA: INFINITY-527

Because we currently determine whether a TaskSpecification has changed by reconstructing it from the launched TaskInfo, there is a bug around Mount Volumes.

If you ask for 16MB of MOUNT volume, but are offered 1GB you'll accept 1GB because MOUNT Volumes are an atomic resource.  Of course, the TaskInfo will be recorded as 1GB of disk.  However on restart of a Task, conversion of the TaskInfo into a TaskSpec for comparison with the original TaskSpec will indicate that an illegal configuration change has occurred.

It will look like the user is now indicating 16MB when the previously indicated 1GB, even though that's not true.

The fix is to do configuration change comparison and not TaskInfo / TaskSpec comparison.  That work is tracked internally at the JIRA indicated.

**Comment by triclambert** [comment]
Done.
