### ISSUE TITLE
Support editing configuration from UI

### ISSUE THREAD

**Issue by frankscholten** [mesosphere/dcos-commons#1920]
Marathon services can be edited from the UI but dcos-commons packages can't. A message is shown which says

```
To update this service's configuration, please update options.json. Run the following CLI command:
dcos cassandra --name=/cassandra update start --options=options.json
```

I understand that this has been disabled because the Marathon config is templated by dcos-commons but from a UX perspective this is quite a step backwards because many services have to configured so they can be exposed via marathon-lb. Now operators have to jump back and forward between the UI, the CLI and the docs to find the options for the given service.

By disabling editing or viewing of configuration the packages are opaque and this hinders troubleshooting.

**Comment by triclambert** [comment]
This is planned for DC/OS 1.11.  /cc @MatApple
