### ISSUE TITLE
Change test.sh --aws to accept a path to a file instead of directory

### ISSUE THREAD

**Issue by seglo** [mesosphere/dcos-commons#2027]
The `test.sh` script requires the path to the **directory** containing the credentials file instead of a path to the file itself.  It looks environment vars were removed as part of this PR:

https://github.com/mesosphere/dcos-commons/pull/2008

I have to workaround providing an `.aws/credentials` file right now because we use the Jenkins credentials plugin to provide a "secrets file" for AWS credentials, but it provides a path directly to a file, and I can't specify the name of the file.  I have to copy the secrets file to a local directory in my Jenkins workspace, name it properly, provide a path to that directory, and then I delete the file so it doesn't hang around after the build.  

It would be preferable for the `test.sh --aws` command to accept a direct link to this file, but I have a feeling it would be a breaking change for you.

/cc @benclarkwood @elezar

**Comment by elezar** [comment]
@seglo, thanks for raising this. Do you mean `test.sh`?

**Comment by elezar** [comment]
For more information, what is the filename that is generated by the Jenkins plugin?

**Comment by seglo** [comment]
Yes, I meant to reference `test.sh`.  The Jenkins credentials plugin appears to generate a random filename for each invocation.  It assigns the path to an ENV VAR that can be referenced in the build.

**Comment by elezar** [comment]
Thanks for the update. How does one get AWS to pick up the randomly generated file?

**Comment by seglo** [comment]
The Jenkins credentials plugin supports a number of different ways to provide secrets.  In order to provide an AWS credentials file I chose to use the "Secrets File" feature, but it's AWS agnostic, so the only way I could use the randomly generated file is if I provided a path directly to it.  For my other AWS deps I've provided the credentials with the environment variables, which the AWS CLI will look for itself.

**Comment by elezar** [comment]
I have also just tested, and it seems as if things work as expected mounting the file directly. Let me create a quick branch for you to test.

**Comment by elezar** [comment]
@seglo would https://github.com/mesosphere/dcos-commons/tree/test-aws-file-mount work for your purposes?

**Comment by seglo** [comment]
@elezar Yes, I think so.  I'll try it out and follow up within the hour.

**Comment by seglo** [comment]
@elezar Yes, this fix works well for me.  Will you PR this to merge to master soon?  I pulled in the commit to a local branch in the meantime.
