### ISSUE TITLE
missing string interpolation in DefaultService diagnostic message

### ISSUE THREAD

**Issue by loren** [mesosphere/dcos-commons#218]
Output in stderr looks like this:
```
[main] INFO org.apache.mesos.specification.DefaultService - Registering framework: %s
```

https://github.com/mesosphere/dcos-commons/blob/master/src/main/java/org/apache/mesos/specification/DefaultService.java#L83

**Comment by activatedgeek** [comment]
@loren I've pushed the fix in an [existing PR](https://github.com/mesosphere/dcos-commons/pull/213). Should be resolved soon.
