### ISSUE TITLE
memory_lock should be exposed as a parameter and default to true

### ISSUE THREAD

**Issue by hanoch** [mesosphere/dcos-commons#2322]
elastic recommendation is to set memory_lock to true, see -
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/setup-configuration-memory.html#mlockall

https://github.com/mesosphere/dcos-commons/blame/c38e10459a04dafe2263b782ed0c4398fc7c7767/frameworks/elastic/src/main/dist/elasticsearch.yml#L18

**Comment by mpereira** [comment]
Hi @hanoch, thanks for bringing this to our attention. We have an internal ticket to address that. You can create further feature requests to [our JIRA](https://jira.mesosphere.com/projects/DCOS_ELASTIC/issues).

Thanks!
