### ISSUE TITLE
Let developers attach a deployment strategy directly to service specification

### ISSUE THREAD

**Issue by loren** [mesosphere/dcos-commons#267]
Currently developers need to use [this constructor](https://github.com/mesosphere/dcos-commons/blob/master/sdk/scheduler/src/main/java/org/apache/mesos/scheduler/DefaultScheduler.java#L105-L119) to instantiate a DefaultScheduler with a PlanManager. 

It seems more straightforward to use [the constructor that takes the ServiceSpecification](https://github.com/mesosphere/dcos-commons/blob/master/sdk/scheduler/src/main/java/org/apache/mesos/scheduler/DefaultScheduler.java#L79-L83) and specify the deployment strategy as part of the service specification.

**Comment by triclambert** [comment]
We have some work underway right now to make this easier.  Stay tuned.
