### ISSUE TITLE
Improvements to `ProcessTask` stability and error handling

### ISSUE THREAD

**Issue by dylanwilder** [mesosphere/dcos-commons#293]
See [here](https://github.com/mesosphere/dcos-commons/blob/99a40b765cf4fc6e4a6226add2f1ccaef2ce22cf/sdk/scheduler/src/main/java/org/apache/mesos/executor/ProcessTask.java#L141).  ProcessTask already has access to the executor diver and this would be a cleaner shutdown. 

[Here](https://github.com/mesosphere/dcos-commons/blob/99a40b765cf4fc6e4a6226add2f1ccaef2ce22cf/sdk/scheduler/src/main/java/org/apache/mesos/executor/ProcessTask.java#L154). This exception serialization is redundant and unexpected and can cause issues in frameworks which expect to carry their own data/serialization standard in this field.

Perhaps [this](https://github.com/mesosphere/dcos-commons/blob/99a40b765cf4fc6e4a6226add2f1ccaef2ce22cf/sdk/scheduler/src/main/java/org/apache/mesos/executor/ProcessTask.java#L81) should be handled in prestart as it has the potential to fail?

Thoughts?

**Comment by dylanwilder** [comment]
I recognize that these are breaking changes and am not sure what procedure is generally followed in this case?

**Comment by dylanwilder** [comment]
[PR](https://github.com/mesosphere/dcos-commons/pull/371)

**Comment by gabrielhartmann** [comment]
Merged #371
