### ISSUE TITLE
Docs: Incorrect command in step 3 of the Readme's quick start

### ISSUE THREAD

**Issue by tobilg** [mesosphere/dcos-commons#333]
At https://github.com/mesosphere/dcos-commons/blob/master/README.md#quick-start in step 3, there's the following:

> Enter your development environment.

`cd dcos-docker/ && vagrant ssh`

I believe it should be `cd tools/vagrant && vagrant ssh` instead, at least that's where I can find the Vagrant box in my local installation.

**Comment by nickbp** [comment]
Yes, the old path wasn't updated when I switched from a system building the image in-place to having a pre-built image downloaded. Should be fixed via PR#334

**Comment by nickbp** [comment]
PS: The instructions printed at the end of running `get-dcos-docker.sh` should be correct, at least
