### ISSUE TITLE
Build process: Clean build directory

### ISSUE THREAD

**Issue by tobilg** [mesosphere/dcos-commons#393]
I just had the issue that the build directory when issuing `./build.sh local` is not cleaned, which lead to the case that there some outdated resource files packaged in the scheduler.zip.

Would it be possible to clean the build directory before each build?

**Comment by gabrielhartmann** [comment]
The build directory is shared by all frameworks and the sdk binaries like `executor.zip` placed there so they may be used from a single location when building the package.  I've tried various modifications to the build script: https://github.com/mesosphere/dcos-commons/blob/master/tools/build_framework.sh#L40

I haven't yet figured out whether it's possible to define a dependency in gradle on a `distribution` of another project.  If you add clean to the referenced line above, the `executor.zip` isn't recreated and packaging fails.

For now, the manual solution is to `./gradlew clean build` from the root to guarantee a clean framework build.

**Comment by keithchambers** [comment]
Can this be closed?
