### ISSUE TITLE
Add HOST and PORTn environment variables

### ISSUE THREAD

**Issue by tobilg** [mesosphere/dcos-commons#398]
I noticed that the scheduler is not setting the typical environment variable known from Marathon, such as `HOST` and `PORTn`.

While `LIBPROCESS_IP` is set (and can probably be used instead of `HOST`, there is afaik no information about used ports. This makes it more or less impossible to use dynamic ports because they are not propagated to the containers.

**Comment by mrbrowning** [comment]
@tobilg, regarding ports, this should be supported directly in the SDK with the introduction of #413 -- under the resources for a task, you can specify resources like so:
```
my-task:
  ports:
    - name: http
      port: 0
```

The result will be a port dynamically allocated based on available ports in the offer being claimed, and an environment variable/value `PORT_http=$DYNAMIC_PORT` set in the task's environment.

**Comment by tobilg** [comment]
@mrbrowning Thanks for the info! I'm using `resource-sets`, can I assume that those work the same way as simply specifying `ports`?

You can have a look at https://github.com/tobilg/dcos-commons/blob/mongodb-replicaset/frameworks/mongodb-replicaset/src/main/dist/svc.yml#L8 if you want.

**Comment by mrbrowning** [comment]
@tobilg yep, the `resource-sets` spec has the same behavior as does specifying resources on a task. Also, static ports work the same way as in the example above, except obviously they're known beforehand -- you'll still get the environment variable set in your task to that port's value.

**Comment by tobilg** [comment]
Sounds great, thanks for implementing this!
