### ISSUE TITLE
YAML service config doesn't use role field / Uncertainty regarding principal/role naming

### ISSUE THREAD

**Issue by tobilg** [mesosphere/dcos-commons#400]
As of [YAMLToInternalMappers.java#L47](https://github.com/mesosphere/dcos-commons/blob/master/sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java#L47) I think there should be a usable `role` from the YAML definition, but as of [RawServiceSpecification.java#L20](https://github.com/mesosphere/dcos-commons/blob/master/sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawServiceSpecification.java#L20) it isn't usable/exposed apparently...

Also, it seems that the role/principals are somehow tied to the package name (although I find it highly unlikely). If I use a different service name than the package name together with the YAML, the  DC/OS Services UI doesn't show the depending task started by the scheduler, but I can see them in the Mesos task list.

**Comment by mrbrowning** [comment]
@tobilg , at least for principal, the default is going to be "$PACKAGE_NAME-principal". I'm not sure what's going on with the UI -- I'd expect that the behavior in that case would just be two frameworks running normally with that same principal -- but I'll attempt to reproduce myself. If you wanted to parameterize the principal on a per-instance basis, you could template your YAML as in [svc.yml#L4](https://github.com/mesosphere/dcos-commons/blob/master/frameworks/kafka/src/main/dist/svc.yml#L4) -- this allows the scheduler to dynamically pull a value from its environment, allowing you to set that environment variable in the marathon configuration at launch time. A `role` field is coming as well, which could be made settable on a per-instance basis in the same way.

**Comment by mrbrowning** [comment]
Regarding the UI issues, the problem there is that both instances you're running probably have the same value for `name` in their YAML defs -- the UI relies on framework name to distinguish framework tasks. As with the principal, this is something you'll want to parameterize via a mustache variable and your marathon config. I'll make sure to update any relevant examples to make it apparent that this is almost always what you want to do with those fields.

**Comment by tobilg** [comment]
@mrbrowning Thanks for the feedback. I'm using 

```javascript
name: "{{SERVICE_NAME}}"
principal: "{{SERVICE_NAME}}-principal"
```

in https://github.com/tobilg/dcos-commons/blob/mongodb-replicaset/frameworks/mongodb-replicaset/src/main/dist/svc.yml#L1-L2. Still, what I think isn't ideal is that the role seems to be implicitly set, and can't be configured via the YAML spec.

I tested it again and it seems to work for my use case now. Not sure if there was an upstream code change, or a change in my configuration with triggered this.

**Comment by tobilg** [comment]
This is no longer relevant, as of the introduction of https://github.com/mesosphere/dcos-commons/blob/master/sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawScheduler.java#L15
