### ISSUE TITLE
Enable caching of URIs

### ISSUE THREAD

**Issue by tobilg** [mesosphere/dcos-commons#402]
As of [scheduler/src/main/java/com/mesosphere/sdk/offer/CommandUtils.java#L16](https://github.com/mesosphere/dcos-commons/blob/master/sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/CommandUtils.java#L24) it seems that the caching of files downloaded from URIs isn't enabled, which leads to potentially long/repeating downloads of the same files.

According to [mesos.proto#L495](https://github.com/apache/mesos/blob/1.1.0/include/mesos/mesos.proto#L495) this could be fixed by setting `cache` to `true`.

**Comment by tobilg** [comment]
Any updates on this possibly? Thanks!

**Comment by shirkevich** [comment]
Look's like @gabrielhartmann working on it in #430

**Comment by tobilg** [comment]
Will this be solved by #430?

**Comment by keithchambers** [comment]
Looks like Uber would like this too for Cassandra.

**Comment by tobilg** [comment]
Probably this can be fixed by just setting cache to true.
