### ISSUE TITLE
Automatically send SUPPRESS and REVIVE calls to suppress Mesos offers

### ISSUE THREAD

**Issue by keithchambers** [mesosphere/dcos-commons#43]
Frameworks using dcos-commons should automatically use SUPPRESS and REVIVE calls without the framework developer needing to do anything.

More details:

https://issues.apache.org/jira/browse/MESOS-3037

With multiple frameworks in a DC/OS cluster, it's critical that frameworks use the SUPPRESS and REVIVE calls to avoid situations where offers timeout before being offered to all frameworks.

**Comment by nickbp** [comment]
Something to think about when this is implemented: The frameworks are currently piggybacking off the periodic offers to run the scheduler. We'd want to have some kind of explicit timer to periodically kick off any maintenance tasks/checks (and those will need to automatically turn offers back on to service things like a task that needs to be brought back up).

**Comment by activatedgeek** [comment]
In the `DefaultScheduler` implementation, I already see `suppressOrRevive` private method calls at appropriate places. Is the implementation still not finalized?

**Comment by triclambert** [comment]
This was completed several days ago [here](https://github.com/mesosphere/dcos-commons/pull/217).  Closing this issue for @mgummelt.
