### ISSUE TITLE
Question regarding task naming / service discovery

### ISSUE THREAD

**Issue by tobilg** [mesosphere/dcos-commons#432]
I was trying to find an intelligent way to receive ip:port information for tasks launched by dcos-commons. I use the following service definition currently: 

* https://github.com/tobilg/dcos-commons/blob/mongodb-replicaset/frameworks/mongodb-replicaset/src/main/dist/svc.yml

While it's possible to derive the `ip:port` info for task by matching the (partial) task name, e.g. `_server`, from the output of the Master's `/master/state` endpoint, which is not ideal IMO.

It seems to be impossible to get this info from

* **The REST API**

There is a `GET /tasks/connection/{taskName}`, which can be used for specific `taskName`s. When queried like `/v1/tasks/connection/mongodb-2-server` in my case, I see `{"dns":"mongodb-2-server.inf-mongodb-replicaset.mesos","ports":""}` as result. The port info is empty. 

Also, there is no endpoint to query the overall connection data (per pod/task). This makes it impossible to use the REST API at the current state to discover the service/task endpoints.

* **Mesos DNS**

As dcos-commons seems to apply a `{podName}-{instanceId}-{taskName}` naming pattern, it isn't possible to use Mesos DNS SRV records to get all endpoints of a specific pod's tasks, but only one-by-one:

```bash
$ dig _mongodb-0-server._tcp.mongodb-replicaset.mesos SRV

; <<>> DiG 9.10.2-P4 <<>> _mongodb-0-server._tcp.mongodb-replicaset.mesos SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8591
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;_mongodb-0-server._tcp.mongodb-replicaset.mesos. IN	SRV

;; ANSWER SECTION:
_mongodb-0-server._tcp.mongodb-replicaset.mesos. 60	IN SRV 0 0 27017 mongodb-0-server-69857-s0.mongodb-replicaset.slave.mesos.

;; ADDITIONAL SECTION:
mongodb-0-server-69857-s0.mongodb-replicaset.slave.mesos. 60 IN A 192.168.200.161

;; Query time: 1 msec
;; SERVER: 198.51.100.1#53(198.51.100.1)
;; WHEN: Mon Jan 09 14:34:06 UTC 2017
;; MSG SIZE  rcvd: 160
```

Ideally, IMO, once could do the following:

```bash
$ dig _server.mongodb._tcp.mongodb-replicaset.mesos SRV
```

so the naming convention would be `_{taskName}.{podName}._tcp.{serviceName}.mesos`

Maybe I did miss the idea on the task/pod service discovery, I'm not sure. It'd be interesting to learn the "official recommended way" to deal with this.

Thanks in advance! cc @gabrielhartmann @mrbrowning

**Comment by nickbp** [comment]
Maybe take a look at `EndpointsResource` which is meant to replace the /tasks/ retrieval: https://github.com/mesosphere/dcos-commons/blob/master/sdk/scheduler/src/main/java/com/mesosphere/sdk/api/EndpointsResource.java

It depends on DiscoveryInfo being populated in the tasks.

**Comment by tobilg** [comment]
Thanks @nickp for the feedback. As I'm using the YAML definitions solely, I'm not using any Java code. So, the YAML doesn't seem to populate the ports?

**Comment by nickbp** [comment]
Ah ok. Yes I think that could be it. Once that's fixed then the /endpoints/ endpoint should start working as well.

**Comment by tobilg** [comment]
According to https://mesosphere.github.io/dcos-commons/swagger-api/index.html there doesn't seem to be a /endpoints endpoint... Should there already be one? 

I guess the Mesos DNS discoverability of all endpoints for all specific task instances of a pod wouldn't work if I'm not mistaken

**Comment by nickbp** [comment]
Whoops, I should've updated that when adding the endpoint. That swagger listing is automatically generated from this manually written source (have been meaning to figure out how to generate this as well...): https://github.com/mesosphere/dcos-commons/blob/master/docs/swagger-api/swagger-spec.yaml

Filed issue for myself: #435

**Comment by tobilg** [comment]
I tested this today: `GET http://172.17.0.2/service/mongodb-replicaset/v1/endpoints`, which yields to

```javascript
{
	"mongodb-replicaset": {
		"direct": ["mongodb-2-server.mongodb-replicaset.mesos:27017", "mongodb-1-server.mongodb-replicaset.mesos:27017", "mongodb-0-server.mongodb-replicaset.mesos:27017"],
		"vip": "mongodb-replicaset.mongodb-replicaset.l4lb.thisdcos.directory:27017"
	}
}
```

So, it seems the final VIP is `mongodb-replicaset.mongodb-replicaset.l4lb.thisdcos.directory:27017`. That's kind of unexpected for me though... Would it mean if I use an empty VIP prefix in the YAML, or omit it completely, that the VIP would be changed to `mongodb-replicaset.l4lb.thisdcos.directory:27017`?

**Comment by tobilg** [comment]
The REST API endpoint for `http://172.17.0.2/service/mongodb-replicaset/v1/tasks/connection/mongodb-2-server` still doesn't return a port number though:

```javascript
{
	"dns": "mongodb-2-server.mongodb-replicaset.mesos",
	"ports": ""
}
```

**Comment by mrbrowning** [comment]
The format of a vip is `$VIP_PREFIX.$SERVICE_NAME.l4lb.thisdcos.directory` -- in this case, the first two happen to be set to the same value, but they don't have to be. It's not possible to omit the prefix, since it's the only parameter that DC/OS lets you set. DC/OS adds everything after the VIP prefix. I'm not sure what you mean about discoverability via DNS -- this should be taken care of by the `/connection`, and we're not able to specify arbitrarily nested DNS domains -- it's `task.service.mesos` only.

**Comment by tobilg** [comment]
@mrbrowning Thanks for the reply! I think it would be great if the VIP format could be "officially" documented somewhere easy to find.

Concerning `/v1/connection`, this seems to be replace now with `/v1/endpoints`? At least I can't seem to access to path, results in a 404 (see also #443).

After reading and trying to understand the sources of the [EndpointsResource class](https://github.com/mesosphere/dcos-commons/blob/master/sdk/scheduler/src/main/java/com/mesosphere/sdk/api/EndpointsResource.java#L112), I figured that I could do a query like `/v1/endpoints/mongodb?format=native`which will return "real" endpoint information:

```javascript
{
	"direct": ["172.17.0.3:27017", "172.17.0.5:27017", "172.17.0.4:27017"],
	"vip": "mongodb.mongodb-replicaset.l4lb.thisdcos.directory:27017"
}
```

I guess that's what I needed, but this is also not really documented somewhere. 

Still, another issue is `/v1/tasks/connection/{taskName}` not returning port numbers IMO.

**Comment by keithchambers** [comment]
Is this resolved and can we close the issue?

**Comment by tobilg** [comment]
Haven't checked in a while if the port is still empty. Is there a way to create a test for that eventually?
