### ISSUE TITLE
CLI command "dcos <packageName> connection" is broken

### ISSUE THREAD

**Issue by tobilg** [mesosphere/dcos-commons#443]
It seems like the `/v1/connection` endpoint [used by the CLI client](https://github.com/mesosphere/dcos-commons/blob/master/cli/commands.go#L139) is no longer available.

At least I see the following error when trying to use the command:

```bash
$ dcos mongodb-replicaset connection
2017/01/11 00:58:36 HTTP GET Query for http://172.17.0.2/service/mongodb-replicaset/v1/connection failed: 404 Not Found
```

As the `/v1/connection` endpoint is also not listed in the [Swagger API docs](https://mesosphere.github.io/dcos-commons/swagger-api/index.html), and I can't find a API resource class under [com/mesosphere/sdk/api](https://github.com/mesosphere/dcos-commons/tree/master/sdk/scheduler/src/main/java/com/mesosphere/sdk/api), I suspect that this was replaced by the (yet undocumented) `/v1/endpoints` endpoint.

**Comment by tobilg** [comment]
Sorry, I just saw that this is already implemented, but not yet activated:

https://github.com/mesosphere/dcos-commons/blob/master/cli/commands.go#L57

The `ConnectionResource` seems to have been removed though, and is apparently no longer usable.

**Comment by nickbp** [comment]
This was in an odd state for a while where the connections endpoint was implemented in the common CLI code while only derived services (Cassandra/Kafka/HDFS) were implementing it as a custom resource. This became a problem when the dcos-commons repo started having frameworks of its own which didn't have that endpoint implemented yet.

The longer term solution is to have everything use the new Endpoints resource that's meant to replace all the current custom Connection implementations with a single universal version, but for now the Connection CLI command should just be removed from the common CLI in favor of having it manually added to CLIs of services that still implement the endpoint.

**Comment by tobilg** [comment]
@nickbp Thanks for the fast feedback. Sorry, but I didn't really understand why you can't activate the `/endpoints` resource in the CLI... Currently it's, as you said, in an odd state, because the ConnectionResource class was already removed.

I was trying to do this on my branch, and use it in my framework, but somehow failed. I guess during the go compile step, it still uses the sources from the dcos-commons GitHub repo.

**Comment by nickbp** [comment]
Oh I see. You should avoid calling HandleCommonArgs as it's due to be removed, and instead add the sections you need directly, see TODO for that function. This is because of how golang works when you aren't manually using vendoring: Changes made in golang code in master IMMEDIATELY take effect in any future downstream builds, so you can end up with new sections in your golang CLI that your Java code doesn't yet implement.

**Comment by nickbp** [comment]
For an example see: https://github.com/mesosphere/dcos-kafka-service/commit/204983ced63c5f1e985af93b14ddb57decb92f5e

**Comment by nickbp** [comment]
FWIW this isn't as much of a problem for services that are in the dcos-commons repo as the Java code is kept up to date in lockstep with the rest of the repo, but it can cause problems when the Java code is in a separate repo and the Java code is referencing a specific dcos-commons Java release.

In theory the real solution would be versioning of the golang CLI alongside the Java library versioning but that hasn't been done yet. I'll file an issue about finding a solution as it's been a problem for a while.

**Comment by tobilg** [comment]
@nickbp Thanks again, and for keeping track of this! So, I'll try to modify my code at https://github.com/tobilg/dcos-commons/blob/mongodb-replicaset/frameworks/mongodb-replicaset/cli/dcos-mongodb-replicaset/main.go#L15 as in the example you linked 👍

**Comment by tobilg** [comment]
@nickbp I changed my CLI implementation now as you hinted. If you have time, please have a look at https://github.com/tobilg/dcos-commons/blob/mongodb-replicaset/frameworks/mongodb-replicaset/cli/dcos-mongodb-replicaset/main.go

It didn't change anything though, the `endpoints` command is still not available. I left everything in there as-is, compared to dcos-commons master.

I'm really puzzled though how I can fix this behavior. This is the CLI output I'm seeing:

```bash
$ dcos package install --cli mongodb-replicaset
172.17.0.2 - - [12/Jan/2017 01:35:41] "GET /stub-universe-mongodb-replicaset.zip HTTP/1.1" 200 -
Installing CLI subcommand for package [mongodb-replicaset] version [stub-universe]
New command available: dcos mongodb-replicaset
[vagrant@dcos-docker-sdk mongodb-replicaset]$ dcos mongodb-replicaset --help
usage: mongodb-replicaset [<flags>] <command> [<args> ...]

Provides CLI integration for the mongodb-replicaset package

Flags:
  -h, --help            Show context-sensitive help (also try --help-long and
                        --help-man).
      --version         Show application version.
  -v, --verbose         Enable extra logging of requests/responses
      --info            Show short description.
      --force-insecure  Allow unverified TLS certificates when querying service
      --custom-auth-token=DCOS_AUTH_TOKEN
                        Custom auth token to use when querying service
      --custom-dcos-url=DCOS_URI/DCOS_URL
                        Custom cluster URL to use when querying service
      --custom-cert-path=DCOS_CA_PATH/DCOS_CERT_PATH
                        Custom TLS CA certificate file to use when querying
                        service
      --name="mongodb-replicaset"
                        Name of the service instance to query

Commands:
  help [<command>...]
    Show help.

  config list
    List IDs of all available configurations

  config show <config_id>
    Display a specified configuration

  config target
    Display the target configuration

  config target_id
    List ID of the target configuration

  connection [<type>]
    View connection information (custom types: foo, bar)

  plan active
    Display the active operation chain, if any

  plan show
    Display the full plan

  plan continue
    Continue a currently Waiting operation

  plan interrupt
    Interrupt the current InProgress operation

  plan force <phase> <step>
    Force the current operation to complete

  plan restart <phase> <step>
    Restart the current operation

  state framework_id
    Display the mesos framework ID

  state status <name>
    Display the TaskStatus for a task name

  state task <name>
    Display the TaskInfo for a task name

  state tasks
    List names of all persisted tasks
```

**Comment by tobilg** [comment]
Nevermind, this was due to an outdated version of the subcommand in `home/vagrant/.dcos/subcommands`... What I think is strange is that the actual subcommand binary doesn't seem to be replace by running

`dcos package install --cli mongodb-replicaset`

Is this the desired behavior?

**Comment by nickbp** [comment]
I'd guess the CLI is refusing to re-install (new builds of the) module if it's already installed. In theory they should have the SHA256 available to check for changes. I'd file a bug against github.com/dcos/dcos-cli/
