### ISSUE TITLE
EndpointsResource returns duplicate entries

### ISSUE THREAD

**Issue by EronWright** [mesosphere/dcos-commons#507]
I notice that the endpoints resource returns duplicate entries after a given task has been recovered.   To reproduce, bring up a task to 'running' state, kill it, wait for the task to recover, then observe the output of `/v1/endpoints`.   You'll see something like this:

```
{
"mypod": {
  "direct": [
    "mypod-0-mytask.myframework.mesos:8080",
    "mypod-0-mytask.myframework.mesos:8080"
  ],
  "vip": "mypod.myframework.l4lb.thisdcos.directory:8080"
  }
}
```

**Comment by loren** [comment]
Thank you for reporting this @EronWright. The issue has been fixed.
