### ISSUE TITLE
Add meaningful descriptions for the Elasticsearch CLI

### ISSUE THREAD

**Issue by tobilg** [mesosphere/dcos-commons#531]
The Elasticsearch CLI submodule is using the dcos-commons default descriptions:

* https://github.com/mesosphere/dcos-commons/blob/master/frameworks/elastic/cli/dcos-elastic/main.go#L17
* https://github.com/mesosphere/dcos-commons/blob/master/frameworks/elastic/cli/dcos-elastic/main.go#L22

I guess it would make sense to update them.

**Comment by keithchambers** [comment]
@loren

**Comment by tobilg** [comment]
Any updates, because this is already in the package: https://github.com/mesosphere/universe/tree/version-3.x/repo/packages/E/elastic/2
