### ISSUE TITLE
[Elastic] Posix Rlimit in Pods

### ISSUE THREAD

**Issue by fperalta2017** [mesosphere/dcos-commons#605]
Set container rlimits in pods causes :  Failed to Validate provided ServiceSpec
com.mesosphere.sdk.specification.validation.CapabilityValidator$CapabilityValidationException: **This cluster's DC/OS version does not support setting rlimits**

**Comment by keithchambers** [comment]
This is expected on a pre-DC/OS 1.9 cluster.
