### ISSUE TITLE
Support for external/docker volumes in pods

### ISSUE THREAD

**Issue by disrani-px** [mesosphere/dcos-commons#916]
The currently supported volumes types (ROOT and MOUNT) don't allow for external volumes to be used for services.

External volumes can be supported by allowing docker volumes to be used in the pods.

The proposal is to allow a DOCKER volume type to be specified along with docker_volume_driver, docker_volume_name and docker_driver_options in the service yaml for the pod specification.

The changes for this proposal can be viewed here:
https://github.com/portworx/dcos-commons/commit/1f1fbbc4c1cc85ce1a4b7efab009ef1d7bc47747

This has been tested with the Cassandra and HDFS service.
Example of changes required in Cassandra service to support this:
https://github.com/portworx/dcos-commons/commit/7f5432b2f00ba30c2d0c527f02a795283b988fe6

**Comment by gabrielhartmann** [comment]
@disrani-px:  These changes look pretty good to me in general.  Out of curiosity why the extensive effort to support upgrade from the old [`dcos-kafka-service`](https://github.com/mesosphere/dcos-kafka-service/) to the new `kafka` implementation?

**Comment by disrani-px** [comment]
@gabrielhartmann: Since these services are in beta users might still choose to use the old service (with changes to run on Docker volumes) and upgrade to this later.
The Cassandra service uses a Docker image, so that should be running UCR.
Your comments actually reflected on the PR I had sent out: https://github.com/mesosphere/dcos-commons/pull/918

**Comment by keithchambers** [comment]
Plan is to support CSI once available in DC/OS.
