### ISSUE TITLE
Include Mesos attributes in the executed tasks as environment variables

### ISSUE THREAD

**Issue by roberveral-datio** [mesosphere/dcos-commons#917]
Currently, with placement rules it's possible to spread tasks in a pod across the cluster based in the Mesos attributes that each node provides. However, the launched tasks doesn't have any idea about the Mesos attributes of the node they're in.

Making the attributes available to the executed tasks could give a resilency improvement for stateful services which are able to consider attributes in their configuration (for example, Elasticsearch allows to configure attributes for each node in the cluster which can be used in the shard allocation awareness property). If you consider an attribute with the availability_zone, it's not enough to spread the nodes across the different availability zones. Besides that, if you can manage it at application level you can, for instance, make sure that no shard and its replica will be in the same availability zone, increasing the service's fault tolerance.

The proposal is to decorate the tasks in an OfferRequirement with the attributes received in an Offer as environment variables when both are linked (in the OfferEvaluator).

We develop it and it's available in the following link: https://github.com/DatioBD/dcos-commons/tree/feature/attributesEnv

We tested it and works properly.

**Comment by gabrielhartmann** [comment]
Thanks @roberveral-datio.  I had a look at your change.

1. There's currently some work underway to consolidate the setting of environment variables on Tasks/Executors in general.  It should be going in pretty shortly.  I've asked that it include addition of attributes, but it may be a bit late, so I would look out for that change before submitting a PR if your'e inclined.  @nickbp could you let him know what you're going to do here?
1. I wouldn't modify the `OfferRequirementProvider` interface, I would just implement the behavior of adding attributes as environment variables as normal default behavior.  This is really what you're doing anyway by always the decoration method in the `OfferEvaluator`.
1. Needs unit tests.

**Comment by roberveral-datio** [comment]
Thanks for the quick feedback!

We made some changes in the same branch to improve where the environment variables are injected (we move it to the LaunchEvaluationStage, to be aligned with the label addition), keeping the interface unmodified. Also, we add a unit test to check that it works.

We would like to send a PR if you need it, so let us know the state and if it could be helpful. ;)

**Comment by keithchambers** [comment]
Hi Robert,

Thank you for proposing this change prior to sending a PR.

There is a new Fault Domains API in design for Apache Mesos that includes support for racks. While it is technically possible to implement similar functionality as proposed with Mesos attributes -- we have made a conscience decision to wait to support racks until this new Mesos Fault Domains API in available in DC/OS. We believe this will yield the best overall user experience.

Thanks,
Keith
